.gitmodules
Makefile
README.md
arp/main.c
bp/main.c
catcher/main.c
config/dynamic.c
config/static.c
cps/main.c
ggu/main.c
gk/main.c
gt/main.c
include/gatekeeper_arp.h
include/gatekeeper_bp.h
include/gatekeeper_catcher.h
include/gatekeeper_config.h
include/gatekeeper_cps.h
include/gatekeeper_ggu.h
include/gatekeeper_gk.h
include/gatekeeper_gt.h
include/gatekeeper_mailbox.h
include/gatekeeper_rt.h
lib/mailbox.c
main/main.c
rt/main.c
setup.sh

These patches add the setup script and Makefile for Gatekeeper so that it is compiled with the DPDK libraries. It also adds a directory structure for the project -- one directory for each functional block, along with lib and include directories.
The entry point to the Gatekeeper program, in main/main.c, for now simply initializes the EAL to show interoperation with DPDK, and also invokes each functional block, which are at this point empty.
There are some other TODO tags added, such as to read in any configuration, set up shared state such as mailboxes, and figure out whether the instance of the program is running the Gatekeeper or Grantor algorithm. More specific TODOs should be added in future patches.
This is also a good time to change the directory structure, naming, etc.

add skeleton code for Gatekeeper

---

README.md
setup.sh

These patches update a file name and give more information about how to set the environmental variables that are required for compiling DPDK applications.

add fixes for README and setup.sh

---

Makefile
gk/main.c
include/gatekeeper_config.h
include/gatekeeper_main.h
include/gatekeeper_net.h
lib/net.c
main/main.c

These patches add the initialization of the ports, and they support for multiple numa nodes. Based on these patches, we can add new functional blocks, and test them using network traffic.
In addition, the patches add the skeleton of the static configuration. The basic idea is that we need to define different configuration data structures and functions for different functional blocks according to the configuration files. To map the functional blocks to lcores, and then queues, we may need to find a smarter way. Currently, the mapping is simply kept in the configuration data structure.
In the GK block example, the patches simply receive a batch of packets and then transmit them into the corresponding TX queues.

add support for initializing the NICs, and a simple GK block example

---

Makefile
README.md
bp/main.c
catcher/main.c
config/dynamic.c
config/static.c
cps/main.c
ggu/main.c
gk/main.c
gt/main.c
include/gatekeeper_bp.h
include/gatekeeper_catcher.h
include/gatekeeper_config.h
include/gatekeeper_cps.h
include/gatekeeper_ggu.h
include/gatekeeper_gk.h
include/gatekeeper_gt.h
include/gatekeeper_lls.h
include/gatekeeper_rt.h
lls/main.c
main/main.c
rt/main.c
setup.sh

The first two commits are improvements on the setup process.
The third commit is to reflect the fact that Gatekeeper has multiple link layer responsibilities: ARP, ND, LACP, etc. Therefore, the ARP functional block is renamed to Link Layer Support.
The config commits take steps toward reading in and using a configuration file. "ensure enough lcores are present" helps set up whether enough lcores have been used to run the program. "add basics for block and lcore config" adds configuration files for every block so that the configuration can assign lcores, enable functional blocks, and run them.

improve setup and flesh out configuration

---

README.md
config/static.c
generate_if_map.c
gk/main.c
include/gatekeeper_config.h
include/gatekeeper_main.h
include/gatekeeper_net.h
lib/net.c
lua/gatekeeperc.lua
lua/net.lua
setup.sh

The point of this pull request is to add more networking configuration that will help the functional blocks, and also to add the beginnings of the BP block.
The operator needs to be able to specify which ports are the Gatekeeper front and back, so the second patch sets up the ability to specify which ports belong to which interface and creates a single identifier for receiving/transmitting.
The BP implementation is only a first effort, as we must answer some key questions before continuing. For example, if ntuple filter is not flexible, how will IPv4 rules be added? Additionally, will this block be able to listen directly on a queue, or will it have to wait for packets to be distributed to it in software? The next step is answering these questions for IPv4 (which will help other blocks), …

add interface abstraction and queue mapping

---

gk/main.c
include/gatekeeper_gk.h
include/gatekeeper_net.h
lib/net.c
lua/gatekeeper_config.lua
lua/gatekeeperc.lua
lua/gk.lua
lua/net.lua
main/main.c

This patch removes the assumption that all blocks use both the TX
and RX queues on both interfaces. It allows each block to be assigned
a queue identifier on a per-interface, per-queue type (RX or TX)
basis. Gatekeeper can now be run with any set of lcores, and permits
different numbers of RX queues and TX queues to be created on the
different interfaces.
To do so, the configuration must be split up. This is because these
functions must be called in this order:
- rte_eth_dev_configure()
- rte_eth_rx_queue_setup()/rte_eth_tx_queue_setup()
- rte_eth_dev_start()
Therefore, the net configuration code must configure each port,
and then allow the functional blocks to run so that they may
call the rte_eth_{r/t}x_queue_setup() functions via assign_queue_id().
Then, the functional blocks wait for …

net: improve queue configuration

---

Makefile
ggu/main.c
gk/main.c
include/gatekeeper_config.h
include/gatekeeper_flow.h
include/gatekeeper_ggu.h
include/gatekeeper_gk.h
include/gatekeeper_ipip.h
include/gatekeeper_mailbox.h
include/gatekeeper_main.h
include/gatekeeper_net.h
lib/flow.c
lib/ipip.c
lib/mailbox.c
lib/net.c
lua/gatekeeper_config.lua
lua/gatekeeperc.lua
lua/ggu.lua
lua/gk.lua
lua/net.lua
main/main.c

The first patch adds support for IP over IP encapsulation for GK block, it supports both IPv4 and IPv6 addresses.  In this patch, the ``struct ip_flow`` is reorganized, since it will be shared by several blocks, so I chose to make it as a library.
The second patch adds a simple GK-GT Unit. The policies will be batched in a packet, for each policy decision, it first calculates the RSS hash value for that IP flow, then the last 7 bits will be used to index the Redirection table entries, where it stores the queue id. With the queue id, we may need to find an efficient way to lookup the corresponding GK block, who is responsible for that IP flow. For now, it simply iterates all the GK instances to find the matched one. With this patch, both RSS and ntuple filters support IPv6 as expected.

Add IPIP encapsulation for GK, and a simple GK-GT Unit

---

Makefile
gk/main.c
include/gatekeeper_lls.h
include/gatekeeper_mailbox.h
include/gatekeeper_main.h
include/gatekeeper_net.h
lib/mailbox.c
lib/net.c
lls/arp.c
lls/arp.h
lls/cache.c
lls/cache.h
lls/main.c
lua/gatekeeper_config.lua
lua/gatekeeperc.lua
lua/lls.lua
lua/net.lua
main/main.c

The LLS block and the ARP cache, implemented to allow other functional blocks to request one-time resolution or to always be notified of updates to an entry.
@mengxiang0811 This patch, not included in this pull request, should give you an idea of how the GK block can subscribe to LLS entries.

add LLS block and ARP

---

include/gatekeeper_lls.h
include/gatekeeper_net.h
lib/net.c
lls/arp.c
lls/arp.h
lls/cache.c
lls/main.c
lua/gatekeeper.lua
lua/net.lua

Enable the operator to specify the subnet prefix length during
configuration, and use that subnet information to decide which
interface to send resolution broadcasts and to determine whether
a received packet's source address is valid.

net: add prefix length to IP addresses

---

config/static.c
ggu/main.c
gt/main.c
include/gatekeeper_config.h
include/gatekeeper_ggu.h
include/gatekeeper_gt.h
include/gatekeeper_ipip.h
lib/ipip.c
lua/gatekeeper.lua
lua/gatekeeper_config.lua
lua/gt.lua
lua/net.lua
lua/policy.lua
lua/policylib.lua

This pull request contains four patches:
Thanks for @cjdoucette careful review, the first patch fixed the bug in IPIP.
The second and third patches adds LPM library as well as decapsulation library, which are used for gt block.
The fourth patch adds support for a simple gt block. For now, it can lookup the policy of a specific destination IP address, and fill up a g``gu_policy`` structure. This can be further used to notify the decision to GK-GT unit.

gt: implement a simple gt functional block

---

Makefile
gk/main.c
include/gatekeeper_gk.h
include/gatekeeper_ipip.h
include/gatekeeper_lpm.h
include/gatekeeper_net.h
lib/ipip.c
lib/lpm.c
lib/net.c
lls/arp.c
lls/nd.c
lua/gatekeeper.lua
lua/gatekeeper_config.lua
lua/gk.lua

These patches add a global LPM table, and integrate LLS to the gk block. For the LPM table, we assume that all the gk instances are running on the same NUMA node, so only one global LPM table is needed.

add LPM table and integrate LLS to gk block

---

Makefile
gk/main.c
gt/main.c
include/gatekeeper_acl.h
include/gatekeeper_lls.h
include/gatekeeper_net.h
lib/acl.c
lib/net.c
lls/cache.c
lls/cache.h
lls/main.c
lls/nd.c
lua/gatekeeper.lua
lua/net.lua
main/main.c

The first patch adds LACP, and takes steps to ensure its requirements are almost always met (but they are not always guaranteed). There is also an important TODO left in LACP, which is to not report dropped packets when LACP is configuring, and to warn the user when LACP configuration is taking too long. This turned out to be harder than I expected and I need to figure out a good way of doing it.
The second patch cleans up some configuration inconsistencies that I noticed in preparation for the third patch.
The third patch adds IPv6 ACLs to GK, GT, and LLS, so that ND packets (and eventually BGP packets) can be recognized quickly. This patch also reverses some changes that were previously made to recognize ND packets in those blocks.

add LACP and IPv6 ACLs

---

config/dynamic.c
config/static.c
include/gatekeeper_config.h
include/gatekeeper_main.h
lua/dylib.lua
lua/dyn_cfg.lua
lua/example_of_dynamic_config_request.lua
lua/gatekeeper.lua
lua/gatekeeper_config.lua

This pull request includes three patches:
The first patch implements a simple dynamic config block. Basically, the dynamic configuration will open one socket, and listens on a configured port. It receives Lua configuration files from clients, and then calls the corresponding functions to list, add, or delete the entries in other functional blocks.
The second patch implements the functionalities to edit LPM table, including add a FIB entry, and delete a FIB entry. Once a FIB entry with action ``GK_FWD_GRANTOR`` is deleted, then it will notify all the GK instances to flush its flow table who has a reference to that FIB entry.
The third patch integrates LLS to the GK blocks using sequential locks. The sequential lock was mainly taken from the Linux kernel, and the original spin lock used to …

Implement the dynamic configuration block and integrate LLS into GK

---

Makefile
gk/main.c
include/gatekeeper_gk.h
include/gatekeeper_sol.h
include/list.h
lua/gatekeeper.lua
lua/gatekeeper_config.lua
lua/gk.lua
lua/sol.lua
sol/main.c

Add the two types of queues needed for a Gatekeeper server: a
priority request queue that is serviced by a Solicitor block,
and granted queues for each GK instance.

gk: add queues and Solicitor block

---

gt/main.c
include/gatekeeper_gt.h
lib/ipip.c

Since Gatekeeper tunnels packets between Gatekeeper and Grantor servers, it should maintain the ECN bits so that congestion management is kept between the source and destination.
To do so, Gatekeeper implements the Full-functionality Option of maintaining the ECN bits for IP-in-IP packets (RFC 3168, 9.1.1).

gk/gt: maintain ECN bits

---

Makefile
cps/main.c
ggu/main.c
gk/main.c
include/gatekeeper_acl.h
include/gatekeeper_net.h
include/gatekeeper_varip.h
lib/acl.c
lib/varip.c
lls/main.c
lls/nd.c

This pull request includes two patches: The first patch fixes a bug in GK block; the second patch adds support for the IP variable headers, including IPv4 option headers, and IPv6 extension headers. Notice that, I have verified that ntuple filters actually support IP variable headers. However, the ACL rules don't support IP variable headers, so for each ACL rule, we need to issue a match function to deal with IP variable headers.

Add support for IP variable headers

---

gk/main.c
lib/net.c

This removes the `TODO` specified in issue #59 because it was already completed by merged pull request #45.

gk/net: remove TODOs that are already finished

---

lib/net.c

For the 82599 NIC, the EtherType value of each EtherType filter should be passed in little endian order according to the 82599 datasheet. This patch verifies that whether this is the case with all NICs that support the EtherType filter, and removes the relevant ```XXX``` in ```lib/net.c```.

net: verify that EtherType filters are little endian

---

gk/fib.c
gk/main.c
include/gatekeeper_fib.h
include/gatekeeper_lls.h
include/seqlock.h

Since the Ethernet header cache can be modified by LLS block, and the GK blocks need to read them to decide the nexthop's link layer header, this patch adds support for the sequential lock to deal with the concurrency.
In addition, some extra modification needed to the patch that edits the GK LPM table, since the operations on GK LPM table will affect the Ethernet header cache.

Integrate LLS to the GK blocks

---

gk/fib.c
gk/main.c
gt/main.c
include/gatekeeper_fib.h
include/gatekeeper_gk.h
include/gatekeeper_gt.h
include/gatekeeper_net.h
lib/net.c
lua/gatekeeper.lua
lua/gt.lua

This pull request includes two patches: the first one fixes a bug in GK block, and the second one integrates the GT blocks with the LLS block.
The basic idea for in the second patch is to keep one hash table per GT instance for caching Ethernet headers to the destinations in the data center protected by Gatekeeper, which avoids synchronization issues among different GT instances.

Integrate the GT blocks with the LLS block

---

cps/main.c
ggu/main.c
gk/main.c
gt/main.c
include/gatekeeper_acl.h
include/gatekeeper_ggu.h
include/gatekeeper_gt.h
include/gatekeeper_lls.h
include/gatekeeper_net.h
include/gatekeeper_varip.h
lib/acl.c
lib/net.c
lls/cache.c
lls/cache.h
lls/main.c
lua/gatekeeper_config.lua
lua/policylib.lua

Before these patches, Gatekeeper NICs were required to support EtherType and ntuple filters for hardware filters. These patches lift this requirement so that other NICs (such as the Amazon ENA) can still run Gatekeeper by filtering packets in software.

Remove requirements for hardware filters

---

Makefile
cps/kni.c
cps/main.c
ggu/main.c
gk/fib.c
gk/main.c
gt/main.c
include/gatekeeper_acl.h
include/gatekeeper_fib.h
include/gatekeeper_gk.h
include/gatekeeper_ipip.h
include/gatekeeper_l2.h
include/gatekeeper_lls.h
include/gatekeeper_net.h
lib/ipip.c
lib/l2.c
lib/net.c
lls/arp.c
lls/arp.h
lls/cache.c
lls/main.c
lls/nd.c
lua/gatekeeper.lua
lua/net.lua

These patches erase the assumption that the link-layer header is always just an Ethernet header, adding the possibility of a VLAN header as well.
I split up the work into two patches because it is a lot of small changes to many files that could be overwhelming to review at once.
The only piece missing is to fill-in the function that crafts the netlink message that adds a VLAN ID to the KNI. The code that I've written for it hasn't worked yet (keep getting operation not supported from the kernel), but it is pretty isolated from the bulk of the patches so a review can be started now if it's convenient.

add support for VLAN

---

gk/main.c
gt/main.c
include/gatekeeper_flow.h
include/gatekeeper_gt.h
lib/flow.c
lua/gatekeeper.lua
lua/gt.lua
lua/policy.lua
lua/policylib.lua

This patch allows GT blocks to reassemble fragmented packets before making a policy decision. It utilizes DPDK IP Fragmentation and Reassembly Library, e.g., ``rte_ipv4_frag_reassemble_packet()`` for IPv4 packets and ``rte_ipv6_frag_reassemble_packet()`` for IPv6 packets.
Moreover, to avoid attackers overflowing the request channel with fragments that never complete, flows associated with fragments that have to be discarded before being fully assembled will be punished.

gt: add support for fragmented packets

---

cps/kni.c
cps/main.c
gk/fib.c
include/gatekeeper_cps.h
include/gatekeeper_fib.h
lua/cps.lua
lua/gatekeeper.lua
lua/gatekeeper_config.lua

This patch allows the CPS block to support editing the routing table of the GK blocks. Basically, this patch takes the routing table updates and passes the useful information to the GK block to update the LPM table. We use functions ``add_fib_entry()`` and ``del_fib_entry()`` to edit GK's routing table.

cps: support editing the routing table of the GK blocks

---

gk/main.c
include/gatekeeper_gk.h
lua/gatekeeper.lua
lua/gk.lua

This patch periodically scans the GK flow tables, and reclaims the expired entries. Moreover, when the table is full, we use a simple solution to alleviate memory pressure by doubling the flow table. Since there is no functions in DPDK hash table to double the hash table size, we have to manually do it.

gk: add support for pruning the flow tables

---

gk/fib.c

This pull request includes two patches: 1) fix bugs in GK block; 2) fix the prefix security hole vulnerability. Basically, it makes sure that prefixes for existing drop and Grantor entries can only be superseded by new prefixes for drop or Grantor entries. The solution is to extend RTE LPM table to have an iterator over its entries.

gk: fix prefix security hole vulnerability

---

cps/kni.c
cps/kni.h
cps/main.c
ggu/main.c
gk/fib.c
gk/main.c
gt/main.c
include/gatekeeper_lls.h
include/gatekeeper_mailbox.h
include/gatekeeper_net.h
include/list.h
lib/acl.c
lib/lpm.c
lib/net.c
lls/cache.h
main/main.c
setup.sh

The DPDK library in Gatekeeper had not been updated in about 1.5 years. These patches update DPDK and make Gatekeeper adhere to the DPDK changes.

Update DPDK library in Gatekeeper

---

README.md

This patch fixes the path for the DPDK network adapters configuration script.

README: fix network adapters configuration script path

---

README.md

Executing the setup script in a subshell causes the
environmental variables RTE_SDK and RTE_TARGET to
be lost when the script completes. Executing the
script in the parent shell makes these variables
persist so that they can be used for compiling and
running Gatekeeper.
This fixes issue #83.

readme: execute setup in current shell

---

include/gatekeeper_acl.h
lib/acl.c
lib/net.c

The IPv4 ACL is only used when the ntuple filter is not
available, so before processing IPv4 packets through
the ACL we need to check whether it is configured.

acl: check whether IPv4 ACL is configured

---

gk/fib.c
gk/main.c

This patch fix the issues related to the function calls:
rte_lpm_is_rule_present() and rte_lpm6_is_rule_present().
The above two functions will return 1 if the rule exists,
0 if it does not, a negative value on failure.
Also, this patch add a newline for all the log messages.
Otherwise, the log message is hard to parse.

gk: fix bugs and style issues

---

config/dynamic.c
main/main.c

This pull request fixes the exceptional abort of Gatekeeper due to a buggy client, and also tests the client request timeout. The current code guarantees that client requests for dynamic configuration must be received under a specified timeout, or the request will be aborted.

Fix the Gatekeeper abort issue and test client request timeout

---

include/gatekeeper_gk.h

This patch drops an unused compile-time parameter.

gk: drop compile-time parameter GK_MAX_NUM_FIB_ENTRIES

---

include/gatekeeper_sol.h
lua/gatekeeper.lua
lua/sol.lua
sol/main.c

When the NIC does not support a guaranteed bandwidth
(such as the Amazon ENA), the operator must calculate
and define the desired bandwidth of the request channel.

sol: add option to define request channel bw

---

cps/kni.c
cps/kni.h
cps/main.c

This patch enables Gatekeeper to be able to set KNI links up without using the link up/down API, and instead restarting the device as shown by the KNI sample application.
This means we don't need to have patches in DPDK adding the link up/down API to the ENA and virtio drivers.
It also removes an `XXX` that turned out to be unneeded.

KNI changes

---

cps/main.c
gk/main.c
gt/main.c
include/gatekeeper_l2.h
lls/main.c

These are logging changes I found are needed when testing Gatekeeper in other environments.
Packets that had no ACL matches were being logged as BGP and IPv6 ND packets that had errors, which was incorrect.
Packets from other Ethernet standards were being received and interpreted as Ethernet II packets, so error messages were being displayed.

Gatekeeper logging changes

---

cps/kni.c
cps/main.c
include/gatekeeper_cps.h
lua/cps.lua
lua/gatekeeper.lua

This patch makes all cps compile-time parameters runtime parameters, except for the mailbox related parameters, which are dealt in a special theme for mailbox (i.e., #126 )

cps: make all compile-time parameters runtime parameters

---

config/static.c
gk/fib.c
include/gatekeeper_l2.h
include/gatekeeper_main.h
include/gatekeeper_net.h
include/seqlock.h
lib/acl.c
lib/flow.c
lib/ipip.c
lib/l2.c
lib/launch.c
lib/lpm.c
lib/mailbox.c
lib/net.c
lua/gatekeeper.lua
lua/net.lua
main/main.c

For Gatekeeper activity that is not related to individual blocks
(such as libraries), this patch adds a dynamic logging type and
removes any lingering references in the Gatekeeper code to
built-in static library log types.

gatekeeper: add dynamic log type for gatekeeper

---

lua/net.lua

The error message is: GATEKEEPER: config: ./lua/net.lua:50:
attempt to index global 'net_conf' (a nil value).

net: fix a small bug

---

lua/example_of_dynamic_config_request.lua

When adding entries to the FIB, the gateway should be in
the same subnet as the IP address of the Gatekeeper server,
and the route prefixes should not contain the IP addresses
of the Gatekeeper server as well. This patch makes the
example FIB entries match the example network configuration.
This closes #173.

lua: match example FIB entries with net config

---

lib/net.c
lua/net.lua

When lua_init_iface() fails, it should cleanup the PCI address
data that it allocated. The Lua configuration files should
also report an error when the interface initialization fails.

net: fix error handling in Lua init

---

setup.sh

generate_if_map.c now expects an output file, so this patch adds an output file for its use in the Gatekeeper setup script.

setup: add output file for interface map script

---

lua/policy.lua
lua/policylib.lua

This patch incorporated Cody's work: [cjdoucette@a9a52a1](https://github.com/cjdoucette/gatekeeper/commit/a9a52a15d3851408014c7a6e75dc2d099ed0a0e3), and closes #157

lua: add example of parsing ICMP/ICMPV6 packets

---

lib/net.c

The RSS and other hardware offload capabilities of devices should be gathered before configuring any of the devices individually. With bonded ports, the possibility of one device supporting an offload but another not supporting the same offload is possible and should be handled depending on whether the offload is critical to Gatekeeper.
The configuration, starting, stopping, and restarting of devices that happens during Gatekeeper's bootstrapping is necessary, but it is also complicated and dependent on driver behavior, time for devices to come back online, etc. Testing with bonded ports revealed some other bugs that don't show up when testing individual devices.

Fix RSS and hardware offload config

---

cps/main.c
ggu/main.c
include/gatekeeper_net.h
lib/net.c
lls/main.c

EtherType and ntuple filters were being applied to the interface
ID instead of individual ports.
This worked for Gatekeeper interfaces with only a single port,
since the interface ID will match the port ID in that case. But
when there are multiple ports, the interface ID identifies the
bonded port, which does not support these filters.
To use these filters when multiple ports are configured, this
patch applies the filters to the ports directly instead of the
Gatekeeper interface IDs.
A filter is only considered supported by a Gatekeeper interface
if all component ports in the interface support it.

net: apply filters to individual ports

---

.gitmodules
README.md
cps/kni.c
cps/kni.h
cps/main.c
gk/fib.c
include/gatekeeper_cps.h
include/gatekeeper_fib.h
lua/cps.lua
lua/gatekeeper.lua
setup.sh

These patches add the first part of the functionality that allows Gatekeeper to interact directly with a userspace routing daemon. The first step is to bind Gatekeeper's Netlink socket to a port ID that the routing daemon can be configured to send to. This allows the Netlink messages to not be interpreted by the kernel.
The next step is to support the functionality required by userspace routing daemons. The one we're targeting, BIRD, performs `RTM_GETROUTE` scans of the routing table to find any manually-added routes or to pick up any other changes that it should be aware of. Therefore, the rest of the patches deal with setting up Gatekeeper to be able to accept a table scan and respond.
While reviewing it might be useful to see the Netlink code in BIRD to see what it is expecting: …

Add routing daemon interaction and route information

---

README.md

Without this package, the `. setup.sh` step reports the error below.
```
configure: error: The client requires GNU Readline library. Either install the library or use --disable-client to compile without the client.
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
```

Building Bird requires libreadline-dev

---

gk/main.c
lib/net.c

When leaving out an IPv6 address on one of the interfaces, the FIB initialization fails and the GK cleanup routine caused a segfault. These patches fixes the cleanup routine and adds a check to make sure the FIB initialization won't fail because of mismatching IP address versions on the interfaces.

Bug fixes concerned with IP address assignment

---

cps/kni.c
include/gatekeeper_cps.h
lib/lpm.c
lua/cps.lua
lua/gatekeeper.lua

The first two patches improve interactions with the routing daemon via Netlink by supporting multiple messages per packet and sending acknowledgements and errors when necessary.
The last patch adds support to receive `RTM_GETROUTE` requests from the routing daemon and respond.

Improve Netlink interactions and support RTM_GETROUTE

---

gk/main.c
include/gatekeeper_gk.h

Map queue ID to GK instance efficiently.
This patch closes #150.

gk: Add queue id to gk instance map

---

lua/gt.lua

After reorganizing the lua directory, we also need to
change the GT lua policy file path to work correctly.

gt: fix a small bug

---

lua/dyn_cfg.lua

Restructure the Lua configuration file for the Dynamic Config block. Rename variables and descriptions to match this wiki page:
https://github.com/AltraMayor/gatekeeper/wiki/Functional-Block:-Dynamic-Config

lua: clean up Dynamic Config file

---

cps/kni.c

When the routing daemon requests routes using RTM_GETROUTE, Gatekeeper
should reply with each route marked as either AF_INET or AF_INET6,
not AF_UNSPEC. Requests for RTM_GETADDR already did this, and other
types of requests do not allow AF_UNSPEC to mean both IPv4 and IPv6.
This patch closes #228.

cps: fix reply to AF_UNSPEC in RTM_GETROUTE

---

cps/kni.c
cps/kni.h
cps/main.c

Since the link layer header length is not counted toward the MTU,
we don't need to account for any difference between the expected
link layer header lengths between the KNI and the physical interface.
This patch closes #234.

cps: make KNI MTU match physical MTU

---

lua/dyn_cfg.lua
lua/examples/example_of_dynamic_config_request.lua
lua/gatekeeper/dylib.lua

The error message when configuring Grantor via dynamic configuration is:
GATEKEEPER DYN CFG: ./lua/gatekeeper/dylib.lua:3: module 'gatekeeper/staticlib' not found

lua: fix configuration bugs

---

gk/main.c

gk: remove assumption that RETA size is 128

---

debian/gatekeeper.service

By ignoring dpdk-devbind errors on ExecStartPre we allow
Gatekeeper to be restarted, as dpdk-devbind will fail due to the
interfaces being already bound.
Other errors are not a problem because if the interface fails to
be bound, Gatekeeper itself will fail to start anyway.

Packaging: ignore dpdk-devbind errors on startup

---

lls/main.c

Commonly, ND router solicitiations and advertisements are
sent to the IPv6 all nodes address (ff02::1). This patch
prevents those messages from cluttering the Gatekeeper log.

lls: drop ND router messages to all nodes addr

---

gk/main.c

When RSS is not available on the front interface, when getting
the responsible GK mailbox the RETA configuration will not be
available. In that case, the responsible GK block is at index 0.

gk: remove RSS check for GK mailbox

---

sol/main.c

Since we want the number of available bytes, we should be multiplying
the number of available cycles times (bytes per cycle) to get a unit
that represents bytes.

sol: fix bug in computing available bytes

---

include/gatekeeper_gt.h
lua/gatekeeper/policylib.lua

gt: upgrade field upper_len of struct gt_packet_headers to uint16_t

---

lua/examples/policy.lua
lua/gatekeeper/policylib.lua

policy: follow network order on packet headers in policies

---

gt/main.c
include/gatekeeper_gt.h
lua/examples/policy.lua
lua/gatekeeper/policylib.lua
lua/gatekeeper/staticlib.lua
lua/gt.lua

gt: add an option to disable packet reassembling at Grantor servers

---

include/gatekeeper_flow_bpf.h

The cycles_per_sec and cycles_per_ms variables were not correctly
visible to BPF programs, which introduced bugs into programs that
depended on their values.
This patch closes #325.

bpf: allow BPF programs to read cycle measurements

---

gt/main.c
lua/examples/policy.lua
lua/gatekeeper/policylib.lua

The issue at #321 was caused by the fact that the byteorder conversion
functions int DPDK (e.g., rte_cpu_to_be_16()) are declared as
'static' functions, so they are not exposed to Lua. This patch
makes these functions available to Lua.
This patch closes #321

policy: make byteorder conversion functions avaiable to Lua

---

bpf/Makefile
bpf/granted.c
bpf/grantedv2.c
bpf/grantedv2.h
bpf/web.c
gk/bpf.c
gk/bpf.h
gk/main.c
include/gatekeeper_flow_bpf.h
lua/gatekeeper/policylib.lua
lua/gk.lua

In production, BPF programs must inspect packet headers and have a more sophisticated bandwidth accounting than the one found in the BPF program `granted.bpf`. This pull request adds all features that have been identified as needed to write production BPF programs and a rich example, namely the BPF program `web.bpf`, to showcase them.

bpf: add features needed to write production BPF programs

---

bpf/bpf_mbuf.h

Previously, we got an error when compiling BPF
program granted.c. This is an issue with the
new headers of DPDK. The upstream issue was filed:
https://bugs.dpdk.org/show_bug.cgi?id=321. The
latest DPDK has fixed this issue.
This patch closes #317

gatekeeper: update DPDK with BPF compiling error fix

---

cps/main.c

There have been small changes to the KNI configuration over time in DPDK, and this patch brings Gatekeeper up to speed with these changes and enables the BIRD program to successfully run.
Without the carrier state (`IFF_LOWER_UP` as opposed to only `IFF_UP`) being set, BIRD does not recognize the interface as up and will not initialize a BGP session. This is now enabled via a module parameter:
https://doc.dpdk.org/guides/prog_guide/kernel_nic_interface.html#kni-default-carrier-state
If the KNI does not have the same MAC address as the Gatekeeper interface, ARP replies to the KNI will not work since the KNI makes the ARP request with a different address than the one in the response (because we relay the ARP response that was originally sent to the Gatekeeper interface). Somewhere along the …

cps: add fixes to CPS block

---

gt/main.c

`rte_ip_frag_table_destroy()` no longer accepts `NULL` as
a valid parameter, and causes a segmentation fault.
Therefore, we must check for a `NULL` parameter.

gt: check frag table before destroying

---

gk/main.c
include/gatekeeper_gk.h
lua/gatekeeper/staticlib.lua
lua/gk.lua

Changing the timeout test for request flows to check
whether the priority is changing enables the GK block to
better prune its flow tables during floods. It also
eliminates the configuration parameter request_timeout_cycles.
Before this patch, this is the performance:
| lcores | table size | GK Mpps rcvd | GK Gibps rcvd | client Mpps sent | client Gibps sent |
|--------|------------|--------------|---------------|------------------|-------------------|
1 | 2^10 | 5.66 | 2.7 | 6.28 | 3.00 |
1 | 2^15 | 5.13 | 2.45 | 5.14 | 2.45 |
1 | 2^20 | 5.29 | 2.52 | 5.93 | 2.83 |
|        |            |              |              |                  |                  |
2 | 2^10 | 5.73 | 2.73 | 5.75 | 2.74 |
2 | 2^15 | 5.84 | 2.78 | 5.89 | 2.81 |
2 | 2^20 | 0.19 | 0.09 | 5.90 | 2.81 |
|        | …

gk: replace request flow expiration test

---

gk/main.c
include/gatekeeper_gk.h

This patch solves the performance degradation issue https://github.com/AltraMayor/gatekeeper/pull/330.
The key insight is that having a single failure per batch
may be bearable. Given a batch of received packets,
it tries to add all new flows, but if one addition fails
for the batch of received packets, it doesn't try all
the other flows to be added in that batch.

gk: drop new flows over batches when flow table is full

---

lib/mailbox.c

When testing Gatekeeper under simulated DDoS attack with
repo https://github.com/cjdoucette/gatekeeper/tree/xia1_gk_test,
Gatekeeper aborted due to too many requests.
After tracing the call graph of the function call ``mb_alloc_entry()``,
we found that the documentation in both the DPDK documentation
http://doc.dpdk.org/api/rte__mempool_8h.html#a6150c041e889498a08d0e0d0769292cb
and its comment for function ``rte_mempool_get()`` were wrong: its return
value is either ``0`` or ``-ENOENT``. However, the true return value is either ``0``
or ``-ENOBUFS`` according to DPDK file ``drivers/mempool/ring/rte_mempool_ring.c``
This patch closes #349.

lib: fix a bug in mailbox

---

gk/main.c
include/gatekeeper_sol.h
sol/main.c

With our new [test environment](https://github.com/cjdoucette/gatekeeper/tree/xia1_gk_test), the mailbox operations are dominating the CPU cycles according to Gatekeeper profiling using Linux perf. To solve the performance issue here, we batch the mailbox operations to send packets to the SOL block in the GK block.
This is the performance before this patch:
| lcores | table size | GK Mpps rcvd | GK Gibps rcvd | client Mpps sent | client Gibps sent |
|--------|------------|--------------|---------------|------------------|-------------------|
|  1  |  2^15  |  3.17  |  1.51  |  11.69  |  5.57  |
|  1  |  2^20  |  3.07  |  1.46  |  12.08  |  5.76  |
|  1  |  2^22  |  2.15  |  1.03  |  11.98  |  5.71  |
|        |            |              |              |                  | …

gk: send requests to SOL in batch

---

gk/main.c

This patch solves the memory loads issue with
extract_packet_info(). Without this patch, we saw that
this function has the highest overhead in terms of
memory loads profiled by Linux perf. After this patch,
it greatly reduces its overhead from ~3.6% to 0.3%, and
Gatekeeper's throughput was improved by ~1.5x.
For performance improvement, please refer to this [comment](https://github.com/AltraMayor/gatekeeper/pull/354#issuecomment-541117370)

gk: prefetch packets before extracting headers' info

---

lua/gk.lua

This patch changes the value of mailbox_max_entries_exp in GK blocks to 14.
With its original value 7, GGU will report the following message:
``GATEKEEPER: mailbox: failed to get a new entry from the mempool - No buffer space available``.

gk: change the value of mailbox_max_entries_exp to 14

---

lib/ipip.c

This patch changes pkt->data_len to pkt->pkt_len
for the total size of the packet in lib/ipip.c ``encapsulate()``.

lib: change field for the total size of the packet

---

gk/main.c
include/gatekeeper_gk.h
lua/gatekeeper/staticlib.lua
lua/gk.lua

This pull request incorporated Cody's pull request #347. Moreover, it adds memory prefetching for flow entry while iterating over the flow table. Also, it heuristically holds the insertion failure state until a certain number of flow entries have expired and been cleaned up.

Scan over flow table entries directly

---

gk/main.c
include/gatekeeper_acl.h
include/gatekeeper_gk.h
lib/acl.c

This first patch in this pull request fixes a subtle bug and the following patches streamline a few things in the code around `gk_proc()`. The central motivation for these rewrites is to smooth out the introduction of the upcoming coroutines.

Streamline code of gk_proc()

---

gk/main.c
include/gatekeeper_gk.h

This pull request was motivated by the discussion [here](https://github.com/AltraMayor/gatekeeper/pull/354#discussion_r338535253). It adds a new field ``uint32_t flow_hash_val`` to ``struct flow_entry``, so that the hash value of the IP flow can be accessed directly and it could save CPU cycles, especially when deleting flow entries from the flow hash table.

Add uint32_t flow_hash_val to struct flow_entry

---

gk/main.c
include/gatekeeper_sol.h
lib/net.c
lua/gatekeeper/staticlib.lua
lua/sol.lua
sol/main.c

The function call common_ring_mc_queue() has very high memory loads
according to Linux perf profiling. This patch tries to remove the use
of struct priority_req, and make struct rte_mbuf itself carry all the
information. Specifically, it uses the private data of the mbuf to carry
the list information and uses the field udata64 in rte_mbuf to carry
the priority inforation. With this optimization, it removes the need for
struct priority_req as well as the mailbox. Instead, it uses the Ring library
to transfer request packets to the SOL block.

sol: solve the contention issue

---

lua/examples/policy.lua

Fix bug of type mismatch between Lua and C, and add an IPv6
simple policy.
This patch closes #379.

lua: update example policy

---

cps/main.c
ggu/main.c
gk/main.c
gt/main.c
include/gatekeeper_cps.h
include/gatekeeper_ggu.h
include/gatekeeper_gk.h
include/gatekeeper_gt.h
include/gatekeeper_launch.h
include/gatekeeper_lls.h
include/gatekeeper_net.h
lib/launch.c
lib/net.c
lls/arp.c
lls/main.c
lls/nd.c
sol/main.c

Below is the performance evaluation of the master branch:
| lcores | table size | GK Mpps rcvd (0%) | GK Mpps rcvd (50%) | GK Mpps rcvd (99%) | GK Mpps rcvd (mean) | cli Mpps sent (0%) | cli Mpps sent (50%) | cli Mpps sent (99%) | cli Mpps sent (mean) |
|--------|------------|-------------------|--------------------|--------------------|---------------------|--------------------|---------------------|---------------------|----------------------|
|  1  |  2^15  |       6.69        |        6.69        |        6.7        |        6.69         |       9.94        |        10.99        |        11.52        |         10.99         | 
|  1  |  2^20  |       6.25        |        6.34        |        6.38        |        6.33         |       9.89        |        10.53        |        11.21 …

gatekeeper: create a mbuf pool for each lcore

---

gk/bpf.c
gk/main.c
include/gatekeeper_gk.h

I anticipate that the implementation of `calc_request_expire_at()` will change, perhaps to something that calculates the number of cycles that are equivalent to three priorities above the current priority (if I understood the instructions correctly). But I'll wait for further directions there.

Add flow entry expiration for requests

---

sol/main.c

The link speed is undefined when req_channel_bw_mbps < 0, this patch
takes this condition into account as well.

sol: fix a bug

---

bpf/grantedv2.h
bpf/web.c
config/dynamic.c
cps/main.c
gk/fib.c
gk/main.c
gt/main.c
include/gatekeeper_net.h
lib/flow.c
lib/mailbox.c
lib/net.c
lls/main.c
lua/gatekeeper/staticlib.lua
lua/net.lua

Grantor blocks currently require hardware support for UDP checksumming. This patch removes that requirement. See the documentation here:
https://github.com/AltraMayor/gatekeeper/wiki/Network#UDP_Checksum_Offloading

Remove UDP checksum hardware requirement

---

gt/lua_lpm.c
gt/main.c

The luaL_error() function calls lj_str_pushvf() function to format
the output string. However, lj_str_pushvf() only handles %s, %c, %d,
%f and %p formats.
This patch closes #410.

gt: fix luaL_error() output

---

gt/lua_lpm.c
lua/examples/policy.lua
lua/gatekeeper/policylib.lua

This is a draft pull request to review this option for fixing this issue. My main concerns are that (1) there's probably a more elegant solution and (2) I don't have a strong understanding or justification for why we're using `struct in6_addr &` as opposed to `struct in6_addr` or `struct in6_addr *`.
Text of commit included below:
The use of references in str_to_prefix6() in Lua is good enough
for getting an IPv6 address struct from C and passing it to
the lpm6_add() function, but they are not sufficient for keeping
those IPv6 addresses in memory to later refer to. Therefore,
when we need to inspect the bytes of the result of str_to_prefix6(),
we need an actual struct in6_addr. This patch expands the return
value of str_to_prefix6() to also return the actual struct in6_addr.
An example of …

lua: improve IPv6 address handling

---

debian/changelog
debian/gatekeeper.install

This PR updates the debian package to install the Lua in gkctl/scripts. It also bumps the package version to -rc2.

Update Gatekeeper Debian package to include gkctl scripts

---

cps/kni.c
gk/fib.c
gk/main.c
include/gatekeeper_log_ratelimit.h
include/gatekeeper_main.h
lib/lpm.c

Note that adding more context sometimes requires the caller of the caller (grandparent caller) of the lookup function to issue the log message, since that's the place where the context makes the most sense.
There is one place -- adding a valid FIB entry -- where this context is needed to clarify that the log message is for a validity check and is not an error. Before this patch, after successfully adding an entry, the log would look like:
```
GATEKEEPER: lpm: IPv4 lookup miss
GATEKEEPER: lpm: IPv4 lookup miss
```
Now it looks like:
```
GATEKEEPER: lpm: IPv4 lookup miss for 172.31.3.0
GATEKEEPER GK: Prefix lookup did not find existing neighbor FIB on front interface, as expected
GATEKEEPER: lpm: IPv4 lookup miss for 172.31.3.0
GATEKEEPER GK: Prefix lookup did not find existing neighbor FIB …
```

lpm: add context to LPM lookup errors

---

gk/bpf.c

Some examples that implement the RFC1624 [Eqn. 4] use the network order:
https://elixir.bootlin.com/linux/latest/source/net/ipv4/netfilter/ipt_ECN.c#L38
This patch removes the byte-order convertion for checksum.

gk: fix checksum issue

---

gk/main.c

After an expired entry is chosen to be deleted and the time
at which it is actually removed, the GK block processes
mailbox commands that could remove the entry. Therefore, we
must check whether the entry still exists before we remove it.
This patch also adds the flow information to the error
message when deleting a flow entry that is not found.

gk: fix bug in flow entry deletion

---

.github/workflows/c-cpp.yml
README.md

This adds automatic compilation for all commits pushed to the `master` branch and for all pull requests to the `master` branch.
It also adds a badge to reflect the current build status.
An example of it running is here:
https://github.com/cjdoucette/gatekeeper/actions/runs/244833770

Add continuous integration for compiling

---

gk/fib.c
lib/net.c

When compiling Gatekeeper on new XIA server with Linux 5.4.0-54-generic
and GCC, there is a compilation error with strncpy(). The issue is
explained here: https://stackoverflow.com/questions/56782248/gcc-specified-bound-depends-on-the-length-of-the-source-argument.

gatekeeper: fix a compilation error with strncpy

---

cps/main.c
gk/fib.c
gk/main.c
gt/main.c
include/gatekeeper_l2.h
include/gatekeeper_net.h
lib/l2.c
lib/net.c
lls/arp.c
lls/cache.c
lls/nd.c
lua/gatekeeper/staticlib.lua
lua/net.lua

gatekeeper: have a VLAN tag for IPv4 and another for IPv6

---

ggu/main.c
gk/main.c
include/gatekeeper_gk.h
include/gatekeeper_sol.h
sol/main.c

The SOL block was originally designed to have a single instance, so the code was not accounting for multiple deallocations. This patch adds the reference count that is employed in the GK and GT blocks to deal with the issue.
While Gatekeeper was not finishing cleanly, this issue was ONLY creating stranger log entries.

sol: proper deallocation of struct sol_config

---

gk/bpf.c
gk/bpf.h
gk/fib.c
gk/main.c
include/gatekeeper_fib.h
include/gatekeeper_gk.h
lua/examples/example_of_dynamic_config_request.lua
lua/gatekeeper/dylib.lua

The Lua function `dylib.c.gk_unload_bpf_flow_handler()` enables the dynamic configuration block to unload a BPF program in runtime.

gk: add dylib.c.gk_unload_bpf_flow_handler()

---

debian/gatekeeper.postinst

During upgrades, generate_if_map will generate an interface map file that's missing the gatekeeper interfaces, because they are already under control of DPDK.
This PR makes it so that generate_if_map will only be executed if the destination file does not exist.

debian: don't run generate_if_map if file exists

---

include/gatekeeper_lls.h
lib/net.c
lls/cache.c

This pull request closes #444.

gatekeeper: add support for /31 (IPv4) and /127 (IPv6) subnet masks

---

cps/kni.c

When a routing daemon scans interfaces requesting
information (RTM_GETLINK), the interface should
report that it is up (and physically connected).
Also, the interface names should be null-terminated
strings to be properly read.

cps: fix bugs in RTM_GETLINK response

---

gkctl/main.c

This PR implements a connection timeout command-line option for `gkctl`. This is useful when running this command right after starting gatekeeper (e.g. via a systemd post-start command). Since it takes a while for gatekeeper to be ready to listen for connections in the dynamic configuration socket, it would be otherwise necessary to run a `sleep` command before `gkctl` in the hopes that we have waited enough for the socket to be ready.
The PR also includes a commit to change `gkctl`'s success return code to `0`, to ease handling errors in shell scripts, and trivial spacing fixes.

gkctl: implement connect wait timeout

---

debian/gatekeeper.cron.daily
debian/gatekeeper.service
debian/patches/01_require_if_map.patch
debian/patches/series

Some fixes and enhancements for debian packages:
1) Ensure the `gatekeeper` unprivileged user has access to `/var/run/gatekeeper` and `/var/run/dpdk/rte`.
This prevents errors such as `GATEKEEPER DYN CFG: Failed to unlink(/var/run/gatekeeper/dyn_cfg.socket) - (Permission denied)` and `EAL: Unable to open directory /var/run/dpdk/rte`.
2) Patch `staticlib.lua` so that it can find `if_map.lua` in the package installation path (`/etc/gatekeeper/if_map.lua`).
3) Add a cron job that removes log files older than 24h. Since gatekeeper "rotates" its own log files (i.e. creates log files names using the current date), this is better handled by a simple `find` command rather than by logrotate.

Debian fixes

---

include/gatekeeper_log_ratelimit.h
lib/log_ratelimit.c
lib/net.c

Before the functional blocks launch (at the end of stage 3),
they are all run on the master lcore (0). Therefore, the rate
limit for lcore 0 is applied to all block initialization and
the network initialization.
In practice, lcore 0 is always assigned to the LLS block,
since we initialize it first. Therefore, the LLS rate limit
is applied to all startup logs.
This patch adds a flag to the log ratelimiting library,
which is only set when initialization is complete. Therefore,
all startup logs will be captured.

log_ratelimit: allow all startup logs

---

debian/gatekeeper.cron.daily

Two fixes in the log cleanup command:
1) The wildcard must be escaped, i.e. `gatekeeper_\*.log`;
2) `-mtime +1` results in only logs older than **2** days being deleted; switch to `-mtime 1` for the intended 24h interval.

debian: fix cron log cleanup command

---

debian/rules

Don't start/enable the systemd unit on package installation, since running gatekeeper before having an adequate configuration is a guaranteed startup error.

debian: don't enable/start service on installation

---

gkctl/scripts/show_arp.lua
gkctl/scripts/show_fib.lua
gkctl/scripts/show_fib6.lua
gkctl/scripts/show_nd.lua
gkctl/scripts/show_neigh.lua
gkctl/scripts/show_neigh6.lua
lua/gatekeeper/dylib.lua

The scripts shipped with `gkctl` were very slow because they would copy the content of the accumulator string multiple times per record of the table being dumped. The new code only concatenates the strings at the very end by calling the efficient `table.concat()` of Lua. The original scripts would take a minute to dump a modest-sized routing table, while the new code accomplishes the same task in less than a second.

Speed up the scripts of gkctl

---

gk/fib.c
gkctl/scripts/show_fib6_grantor.lua
gkctl/scripts/show_fib_grantor.lua
lua/gatekeeper/dylib.lua

As pull request #489 brought up, the FIB iterator is the most demanding iterator available through the dynamic configuration block. This pull request improves the code of this iterator to further save time.
This pull request also adds two new `gkctl` scripts to only list grantor FIB entries. Not only are these new scripts useful in production, but they also serve as examples of how to filter any subset of FIB entries.

Improve the FIB iterator available for the dynamic configuration block

---

cps/rd.c
gk/fib.c

The iterators of the FIB implemented in the CPS and GK blocks were reporting a wrong prefix length of /0 for IPv6 FIB entries.

gatekeeper: report the right prefix length of FIB entries

---

cps/rd.c
gk/fib.c
include/gatekeeper_lpm.h

This pull request:
1. adds support to the RTNetlink flags `NLM_F_EXCL`, `NLM_F_REPLACE`, and `NLM_F_CREATE` for `RTM_NEWROUTE` requests;
2. Removes the requirement of interface information for `RTM_NEWROUTE` requests;
3. Protects grantor entries from being edited by routing daemons.

cps: improve handling of RTNetlink edit requests

---

cps/rd.c
gk/fib.c
gkctl/scripts/summarize_fibs.lua
include/gatekeeper_fib.h

While Gatekeeper ignores the RTNetlink field `RTA_PRIORITY`, routing daemons keep track of this field. So this pull request saves it in the FIB.
A script to quickly inspect the whole FIB is also added.

cps: support the RTNetlink field RTA_PRIORITY

---

cps/main.c

The capability `CAP_SYS_MODULE` is needed to remove the `rte_kni` kernel module while exiting.
This pull request avoids the following log entry:
`GATEKEEPER CPS: Error removing rte_kni: Operation not permitted`

cps: request capability CAP_SYS_MODULE

---

gt/lua_lpm.c
gt/main.c
include/gatekeeper_gt.h

The Lua states that run policies are created during the initialization of Grantor, and during policy reloads. In the former case, the creation is done on the master lcore. In the latter case, on the lcore of the dynamic configuration block. Thus, the code has to guess the lcore that actually runs the policy while creating LPM tables.
This patch avoids the guessing by adding the running lcore ID to the registry of the lua states, and making the Lua LPM library to
use this information.

gt: correct NUMA node of LPM tables

---

config/dynamic.c
gkctl/scripts/reload_policy.lua
gt/main.c

When more hugepages are needed after boot and a Grantor server is running with a non-root user, the following log entry may show up in the log: `EAL: Couldn't get fd on hugepage file`. The previous log entry is likely followed by the following entry: `LPM: LPM memory allocation failed`.
This pull request addresses this problem and adds a `gkctl` script to request the reload of the policy.

gt: allow policies to request more hugepages after boot

---

lua/gatekeeper/dylib.lua

This change allow the function to actually return a value when `is_returned` is `true`.

lua/dylib: return value from update_gt_lua_states_incrementally

---

gt/lua_lpm.c
lua/examples/policy.lua

This pull request adds information to some of the error messages of the Lua `lpmlib` to help diagnoses in production, fixes a bug while passing IPv6 addresses from Lua policies to `lpmlib`, and makes `lpmlib` accepting IPv6 addresses in any type.

Review Lua lpmlib

---

include/gatekeeper_lls.h
lls/cache.c

Gatekeeper only handles a couple of ICMP packets, and drops all the rest. This patch forwards the rest of the ICMP packet to
the KNI interfaces, so the kernel can use them. This enhances diagnosis and IPv6 compatibility.
As a bonus, this patch simplifies Gatekeeper's code since Gatekeeper no longer has to deal with ping and other ICMP cases.

cps: push not-handled ICMP packets to KNI interfaces

---

cps/main.c
include/gatekeeper_cps.h
lua/cps.lua
lua/gatekeeper/staticlib.lua

Instead of having a filter for a given TCP port, this patch forwards all TCP packets to the KNI interfaces. This way, even fragmented packets are delivered to the KNI interfaces and Gatekeeper users can use multiple daemons.

cps: forward all TCP packets the KNI interfaces

---

lib/acl.c

Combining ACL types reduces effort while classifying packets, and increases the number of packets passed to callback functions.
While the impact of this pull request varies with what the NICs support, it's expected to affect IPv6 more than IPv4 ACL rules. For example, consider the ACLs for IPv4 and IPv6 for front and back interfaces on our XIA1 server before this pull request:
```
(gdb) p config.front.ipv4_acls
$1 = {acls = {0x17044d140, 0x227da60640, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, 
funcs = {0x5555556e8f7f <drop_unmatched_pkts>, 0x55555569d389 <submit_icmp>, 0x5555556221ab <cps_submit_direct>, 0x0 <repeats 13 times>},
ext_funcs = {0x0, 0x55555569e8cf <match_icmp>, 0x555555627067 <match_tcp4>, 0x0 <repeats 13 times>},
func_count = 3, enabled = true}
(gdb) p config.front.ipv6_acls
$2 = …
```

acl: combine ACL types

---

gk/fib.c
gk/main.c
include/gatekeeper_fib.h

Field neigh6 is ONLY an alias to field neigh.

gk: drop field neigh6 of struct gk_fib

---

lib/l2.c
lib/net.c

Gatekeeper does not rely on those fields, but it could be confused by those fields if routers were using them.

net: clear priority and CFI fields of VLAN headers

---

gk/main.c
lib/flow.c

When a Gatekeeper server is going to forward a packet from an interface to a neighbor of the other interface, Gatekeeper looks up the MAC address of that neighbor in the known-neighbor subtable of the FIB.
Gatekeeper has wrongly assumed that any neighbor is always known. This patch drops packets destined to unknown neighbors.

gk: only forward to known neighbors

---

gk/fib.c

This pull request is a collection of patches to improve the code of `gk/fib.c` and a patch to check the type of a FIB entry before updating it. This last patch avoids memory corruption memory when a wrong prefix is passed to the FIB.

gk: improve the code of the FIB table

---

gk/fib.c
gkctl/scripts/check_fibs.lua
include/gatekeeper_fib.h
lua/gatekeeper/dylib.lua

The first two patches tighten up the code in `gk/fib.c`, whereas the third patch adds the FIB IDs of the FIB entries to the iterators available to the dynamic configuration block.

gk: add FIB ID to iterators

---

gk/fib.c

Calling `del_fib_entry_locked()` on a neighbor prefix would've put Gatekeeper's FIB table in an inconsistent state. Besides this problem, there's no need to remove neighbor prefixes. This pull request forbids the operation.

gk: forbid del_fib_entry_locked() to delete neighbor entries

---

gk/fib.c
lls/main.c

This pull request reduces log in production by lowering the priority of some log entries that do not add much in production,
are logged often, and are unavoidable.

Gatekeeper: optimize logging for production

---

gk/main.c
include/gatekeeper_flow.h
include/gatekeeper_gk.h
lib/flow.c

On rare occasions, the flow table of a GK instance may be corrupted. This has been seen in a Gatekeeper server in production running for a month without a reboot. The problem can be identified with the presence of log entries similar to the one below:
```
GATEKEEPER: flow: The GK block failed to delete a key from hash table at gk_del_flow_entry_from_hash: No such file or directory
for the flow with IP source address 1.1.1.1, and destination address 2.2.2.2
```
The IP addresses in the log entry above have been anonymized.
While Gatekeeper keeps going, if corruption keeps happening, a reboot will be eventually required. If no more corruption is added, the log of Gatekeeper will be full of warnings and errors.
This patch identifies corruption, heal the flow table, and log information that …

gk: heal corrupted flow tables

---

cps/rd.c

`rd_getroute_ipv6()` is not releasing the lock after listing the IPv6 LPM table.  This patch unlocks the lock before `rd_getroute_ipv6()` returns.
Pull request #529 introduced this bug.

cps: avoid deadlock after listing IPv6 LPM table

---

bpf/Makefile
bpf/tcp-services.c
lua/gatekeeper/policylib.lua
lua/gk.lua

The BPF `tcp-services.c` behaves like the BPF `web.c` but with listening and remote ports coming as parameters.

bpf: add BPF tcp-services.c

---

lib/net.c

Knowing which filters NICs support helps with diagnosis and debugging.

gatekeeper: log filters that NICs support

---

cps/rd.c
gk/fib.c
lib/flow.c
lib/net.c

This patch is meant to help to collect information for issue #585, and to allow Gatekeeper servers in production to keep running even if they find the routing table is corrupted while dumping it.
This patch also pushes issue #572 forward.

gatekeeper: drop rte_panic() while dumping the routing table

---

Makefile
cps/rd.c
gk/fib.c
gk/main.c
include/gatekeeper_fib.h
include/gatekeeper_log_ratelimit.h
include/gatekeeper_lpm.h
include/gatekeeper_rib.h
lib/rib.c

This pull request replaces the calls to the LPM iterator present in Gatekeeper's custom DPDK with a Routing Information Base (RIB). This is one step toward no longer having a custom DPDK for Gatekeeper. This work has been scheduled for Gatekeeper v1.2, but it is being brought to 1.1 due to issue #585.
This pull request closes #542.

gk: add a Routing Information Base

---

gk/main.c

This patch replaces `rte_hash_lookup_bulk_with_hash()` from our DPDK patches with `rte_hash_lookup_with_hash_bulk()` from mainline DPDK.
This patch closes #597.

gk: adopt rte_hash_lookup_with_hash_bulk()

---

cps/rd.c
gk/fib.c
include/gatekeeper_fib.h
include/gatekeeper_rib.h

The code around the FIB has tried to do some of the work related to adding and removing entries without holding a lock. The intention was to be faster, but the savings are small since there are way more readers than writers. Moreover, the risk of crashing Gatekeeper is too high. This pull request conservatively protects this code by acquiring the lock before it.
In addition, all FIB lookups that are not for incoming packets are rewritten to use the Routing Information Base added in pull request #594. This prepares Gatekeeper to eventually support NICs that can offload LPM lookups.

fib: review lock requirements

---

gk/fib.c
include/gatekeeper_fib.h

The original `get_empty_fib_id()` prioritizes having all fib entries close together.  This strategy is too slow for large routing tables.  Having a speedy `get_empty_fib_id()` is critical to quickly populate the routing table when Gatekeeper boots up.
To compare performance, a production routing table with 891094 prefixes was loaded via the Dynamic Configuration block. With the original `get_empty_fib_id()`, the load took 26 minutes and 10 seconds.  With the speedy `get_empty_fib_id()`, the same load took 4 minutes and 26 seconds. That is almost 6 times faster!

gk: speed get_empty_fib_id() up

---

gk/fib.c
include/gatekeeper_fib.h

The log entries of the FIB are part of the day-to-day interactions between network administrators and Gatekeeper servers. This commit improves these entries to bring them up to the new log format and adds information to these entries.
This commit also improves the strings of Lua errors associated with the FIB, reviews some error codes, and adds `const` to the parameter `struct ip_prefix` of many FIB functions.

gk: improve log entries of the FIB

---

ggu/main.c
gk/main.c
include/gatekeeper_flow.h
include/gatekeeper_net.h
lib/flow.c
lib/net.c
lua/gatekeeper/staticlib.lua
lua/net.lua

The original code assumes all RSS hash keys are 10 * 4 = 40 bytes. While this assumption has held well through the years, recent NICs have keys that are 13 * 4 = 52 bytes long. The length of RSS hash keys is always a multiple of 4 (i.e. `sizeof(uint32_t)`.
This pull request enables front and back interfaces to have different RSS hash keys of different lengths. However, if an interface is
bonded, all the keys of the ports must have the same length. Otherwise, there would not be a way to find the RSS hash of
a packet in software since there would be multiple values depending on where the packet arrived at the server.

gatekeeper: support variable sizes of RSS hash keys

---

include/gatekeeper_net.h
lib/net.c
lua/gatekeeper/staticlib.lua
lua/net.lua

The PMD i40e does not support the RSS hash functions `ETH_RSS_IPV4` and `ETH_RSS_IPV6` (i.e., RSS hash for IPv4 or IPv6 non-fragmented packets).  So Gatekeeper cannot work.
Nevertheless, i40e has an alternative way to set the needed RSS hash.  This patch adds the parameter `alternative_rss_hash` to `struct gatekeeper_if` to ask Gatekeeper to try this alternative hash.
The implemented solution is based on the reply to the question  [How to set up RSS hash fuction in XL710 to receive IPv4 flow type?](https://stackoverflow.com/questions/42342723/how-to-set-up-rss-hash-fuction-in-xl710-to-receive-ipv4-flow-type) on Stack Overflow.

lib/net: add support to the PMD i40e

---

gt/lua_lpm.c

This commit makes `l_lpm_lookup()` and `l_lpm6_lookup()` report error codes.
This commit closes #632.

gt: fix l_lpm_lookup() and l_lpm6_lookup()

---

include/gatekeeper_main.h
lib/log_ratelimit.c

Having the log level on each logged string enables network operators to quickly assess the gravity of log entries.
This commit closes #616.

log: add log level to log entries

---

lib/mailbox.c
lls/cache.c
lls/cache.h
lls/main.c

This pull request addresses issue #288. `lls_req()` has no sister functions at the time of this pull request because they have been eliminated as the code evolved.
This pull request closes #288.

lls: drop lls_req()

---

.gitmodules

This new branch for Gatekeeper v1.2 drops patches that are no longer needed, and adds a fix for the ICE driver. More information on the ICE driver is available on issue #634.

dpdk: update branch for Gatekeeper v1.2

---

lib/fib.c

When a Gatekeeper server is set to work with either IPv4 or IPv6 only, `fib_free()` is called on an uninitialized FIB. This pull request avoids a segmentation fault by following the example of `free(3)` that ignores `NULL`.

lib/fib: fib_free() must be okay with uninitialized FIBs

---

gk/main.c
include/gatekeeper_log_ratelimit.h
include/gatekeeper_main.h
lib/log_ratelimit.c
main/main.c

Adding date and time to log entries helps one to investigate bugs during development and issues in production.
This commit closes #615

log: add date and time to log entries

---

.github/workflows/c-cpp.yml
README.md

pkg-config is needed to bridge DPDK and Gatekeeper's Makefile.

gatekeeper: add pkg-config as package dependency

---

gk/main.c
include/gatekeeper_hash.h
lib/hash.c

This patch ensures that the library only returns user (or entry) indexes to library users. The code returned bucket indexes at some locations, which broke library users.

lib/hash: avoid mixing bucket and user indexes

---

gk/main.c

When a flow table is full, sending packets of flows not backed by a flow entry to a Grantor server is counterproductive because
1. it stresses the request channel; and
2. it often wastes the policy decisions that cannot be installed to the flow table since the table is full.

gk: drop packets of flows not backed by a flow entry

---

gk/main.c

In rare situations, `hs_hash_add_key_with_hash()` will try to add a flow already in the flow table. Callers of `hs_hash_add_key_with_hash()` ignored these cases and discarded the associate updates.
The reason for not handling those cases was that `rte_hash_add_key_with_hash()` does not return the entry ID when it already exists in the table, and adding a lookup to the hot path was not desirable. However, `hs_hash_add_key_with_hash()`, from the new hash table library, provides the entry ID when it is already in the table.

gk: handle hs_hash_add_key_with_hash() == -EEXIST

---

gk/main.c
gt/main.c
include/gatekeeper_log_ratelimit.h
include/gatekeeper_main.h
include/gatekeeper_net.h
include/gatekeeper_sol.h
include/list.h
lib/log_ratelimit.c
lib/net.c
lua/gatekeeper/staticlib.lua
lua/net.lua
lua/sol.lua
sol/main.c

The original version of the bonding driver required applications to set many parameters of the members of a bonded interface directly. This is no longer the case, and this pull request reviews the initialization code of network interfaces to accomplish the following:
1. Simplifying the initialization code by leveraging the current bonding driver;
2. Fixing a LACP bug when a bonded interface has two or more physical interfaces and all support multicast;
3. Improving transmission capacity of bonded interfaces by adding IPv4 and IPv6 addresses into the balancing hash;
4. Reporting MAC addresses of the interfaces to enable diagnoses;
5. Monitoring the state of the links through interruptions;
6. Updating the calculation of the bandwidth of the request channel;
7. Fixing miscalculations in the …

gatekeeper: rewrite initialization of network interfaces

---

include/gatekeeper_log_ratelimit.h
include/gatekeeper_main.h
lib/log_ratelimit.c
lib/net.c

This commit drops `MAIN_LOG()` and makes calling `G_LOG()` in non-lcore contexts safe because it is very error prone to identify when one should use `MAIN_LOG()` instead of `G_LOG()`. For example, `lib/net.c:lsc_event_callback()`, which runs in a non-lcore context, calls `log_if_name()`. But `log_if_name()` uses `G_LOG()` because it is also called in lcore contexts.

log: merge MAIN_LOG() into G_LOG()

---

lib/net.c

The newer i40e driver of DPDK resets the global registers while starting a port. This patch updates the global registers of an i40e NIC after front and back interfaces have started.
This pull request closes #685.

lib/net: correct RSS hash of i40e NICs

---

lib/net.c

While tuning the number of instances of the functional blocks, the configuration may exceed the maximum number of queues that the NICs support. When this happens, the error message in the log is not informative. For example:
```
Ethdev port_id=0 nb_rx_queues=43 > 8
Main/0 2024-06-25 17:07:22 ERR init_iface(back): failed to configure interface (errno=22): Invalid argument
```
This commit identifies the problem and gives a helpful error message:
```
Main/0 2024-06-25 17:38:22 ERR check_if_queues(back): the current configuration requires 43 RX queues, but the interface supports at most 8 RX queues. It may be possible to reduce the number of instances of the GK or GT functional block to reduce the number of queues. If not, more capable NICs are needed.
Main/0 2024-06-25 17:38:22 ERR …
```

lib/net: give an informative error when not enough queues

---

bpf/grantedv2.h
bpf/libicmp.h
bpf/tcp-services.c

`clang` version 18.1.3 on Ubuntu 24.04.1 LTS ignores the hint `inline` while compiling `bpf/tcp-services.c`, which, in turn, leads to Gatekeeper servers to fail to load that BPF. `clang` does this because some inline functions in `bpf/tcp-services.c` increase the number of jumping states a lot (see `is_port_listed_forward()` and `is_port_listed_back()`).
Although `clang`'s decision is smart from an optimization point of view, it breaks Gatekeeper because DPDK's BPF library does not support a BPF function to call another BPF function.

bpf: force inline functions

---

lib/net.c

IPv6's protocol ND requires multicast.
Most DPDK's drivers have multicast enabled by default, but a few drivers have it disabled by default.
Drivers known to have multicast disabled by default are the bonding driver when LACP is being used and the i40e driver.

lib/net: enable multicast addresses if IPv6 is enabled
