AltraMayor/gatekeeper

.gitmodules
Makefile
README.md
config/static.c
gk/main.c
include/gatekeeper_gk.h
include/gatekeeper_net.h
lib/net.c
lua/gatekeeper_config.lua
lua/gatekeeperc.lua
lua/gk.lua
lua/net.lua
main/main.c
setup.sh

The first three commits mainly aim at supporting LuaJIT submodules, and fix the setup.sh and README files.
The  fourth commit actually removed some unused headers.
The fifth commit adds support to configure gatekeeper via Lua scripts. Now, we are ready to use LuaJIT FFI library to call functions defined in the C functional blocks.
The sixth commit configured GK block via Lua scripts.
The seventh commit configures the network via Lua scripts.

Configure the project via Lua scripts

---

gk/main.c
include/gatekeeper_gk.h
include/gatekeeper_main.h
include/gatekeeper_net.h
lib/net.c
lua/gatekeeperc.lua
lua/gk.lua
lua/net.lua
main/main.c

This pull request tries to add the basic algorithm for GK block.
Commit 1: tries to remove unused fields from Lua scripts. When I tried to remove the internal fields in ``struct gatekeeper_if``, the program quits with a segment fault. It seems that the Lua script function ``init_iface()`` cannot obtain the address of the ``front`` and ``back`` interfaces in it.
Commit 2: tries to obtain the system time resolution, e.g., ``cycles_per_sec`` and ``picosec_per_cycle``. These metrics are system dependent, so I wrap them up as a function.
Commit 3: tries to implement the basic algorithm of a GK block. To make this component complete, we still need to implement other components like ``RT``, ``GK-GT Unit``, ``IP over IP Encapsulation/Decapsulation``, and ``Request/Granted Queues``.

Implement the basic algorithm for GK block

---

ggu/main.c
gk/main.c
include/gatekeeper_net.h
lib/net.c
lua/gatekeeperc.lua
lua/net.lua
main/main.c

The patch **lls: add initialization and cache** creates the basic shape of the LLS block and creates a resolution cache. The patch **lls: add ARP processing and cache** instantiates one of those caches for ARP entries and adds the ability to send/receive ARP packets.

touch up network configuration

---

Makefile
gk/main.c
gt/main.c
include/gatekeeper_ipip.h
include/gatekeeper_lls.h
include/gatekeeper_net.h
lib/ipip.c
lib/net.c
lls/arp.c
lls/cache.c
lls/cache.h
lls/main.c
lls/nd.c
lls/nd.h
lua/gatekeeper.lua
lua/net.lua

These patches fix small bugs and stylistic issues in net and lls, and also add new functionality in the bonded interface driver as well as support for ND to resolve IPv6 addresses.

fixes and additions for net and lls

---

Makefile
README.md
cps/kni.c
cps/kni.h
cps/main.c
ggu/main.c
gk/main.c
gt/main.c
include/gatekeeper_acl.h
include/gatekeeper_config.h
include/gatekeeper_cps.h
include/gatekeeper_lls.h
include/gatekeeper_net.h
include/list.h
lib/acl.c
lib/net.c
lls/arp.c
lls/main.c
lls/nd.c
lua/cps.lua
lua/gatekeeper.lua
lua/gatekeeper_config.lua

This pull request adds almost all of the CPS block, and also includes some related changes to the LLS block and the ACL library.
The only component left of the CPS block is to take the routing table updates and pass the useful information to the GK block to update the LPM table.

add CPS block

---

gt/main.c

This patch fixes small bugs in GT block.

gt: fix some bugs

---

lib/net.c

This PR solves issue #72 Randomize the secret key of RSS hash.

lib/net: Randomize the secret key of RSS hash

---

gkctl/main.c
setup.sh

gatekeeper: add a simple client

---

gk/fib.c

This patch closes #111. The root cause of this bug was:
the parameter 'struct ipaddr *addr' in ether_cache_put()
is from the Ethernet cache entry. After calling put_xxx(),
it's possibly that gk_arp_and_nd_req_cb() is called before
rte_hash_del_key(). In this case, the 'addr' will be reset,
so that the hash key (i.e., addr->ip.v4 or addr->ip.v6) becomes invalid.
The solution is to make a copy of the hash key, so that
even the cache entry is reset, we can still remove the key-value
pair from the hash table.

gk: fix FIB deletion bugs

---

include/gatekeeper_net.h
lib/net.c
lua/gatekeeper.lua
lua/net.lua

net: guarantee entropy of getrandom(2) in production

---

Makefile
gk/fib.c
gt/main.c

Update Gatekeeper and DPDK to use the latest DPDK release

---

Makefile
gk/main.c
include/gatekeeper_gk.h
include/gatekeeper_ratelimit.h
lib/ratelimit.c
lua/gatekeeper.lua
lua/gk.lua

gk: decrement the IP TTL/hop_limits field

---

config/dynamic.c
gt/main.c
include/gatekeeper_config.h
include/gatekeeper_gt.h
lua/dyn_cfg.lua
lua/example_of_dynamic_config_request.lua
lua/gatekeeper.lua
lua/gatekeeper_config.lua
lua/gt.lua

dyn_cfg: add dynamic config support for Grantor

---

config/dynamic.c
config/static.c
cps/kni.c
ggu/main.c
gk/fib.c
gk/main.c
gt/main.c
include/gatekeeper_config.h
include/gatekeeper_fib.h
include/gatekeeper_ggu.h
include/gatekeeper_gk.h
include/gatekeeper_sol.h
lib/acl.c
lib/net.c
lls/main.c
lua/cps.lua
lua/example_of_dynamic_config_request.lua
lua/gatekeeper.lua
lua/gatekeeper_config.lua
lua/ggu.lua
lua/gk.lua
lua/lls.lua
lua/policy.lua
main/main.c
sol/main.c

This pull request removes unnecessary XXX tags and matches all tags with issues on GitHub.
This completes the review of all TODO and XXX tags.

Match TODO and XXX tags to issues

---

config/dynamic.c
gk/fib.c
include/gatekeeper_fib.h
include/gatekeeper_net.h
lib/luajit-ffi-cdata.c
lib/net.c
lua/dylib.lua
lua/example_of_dynamic_config_request.lua

gk: add support for dumping GK FIB entries

---

config/static.c
gk/fib.c
gt/main.c

When trying to send the ``lua/example_of_dynamic_config_request.lua`` script multiple times to Gatekeeper, there will be errors. This pull request addresses these bugs.

gk: fix some bugs

---

gk/fib.c

gk: fix fib deadlock issue due to a Lua error

---

Makefile
config/dynamic.c
config/static.c
gt/main.c
include/gatekeeper_config.h
include/gatekeeper_main.h
lib/launch.c
lua/dyn_cfg.lua
lua/gatekeeper.lua
main/main.c

Config: make all compile-time parameters runtime parameters

---

Makefile
config/static.c
include/gatekeeper_lls.h
include/gatekeeper_main.h
include/gatekeeper_net.h
lib/acl.c
lls/main.c
lua/gatekeeper.lua
lua/net.lua
main/main.c

gatekeeper: Redirect DPDK log to file

---

Makefile
config/dynamic.c
cps/main.c
ggu/main.c
gk/main.c
gt/main.c
include/gatekeeper_config.h
include/gatekeeper_cps.h
include/gatekeeper_ggu.h
include/gatekeeper_gk.h
include/gatekeeper_gt.h
include/gatekeeper_lls.h
include/gatekeeper_log_ratelimit.h
include/gatekeeper_main.h
include/gatekeeper_sol.h
lib/log_ratelimit.c
lls/main.c
lua/cps.lua
lua/dyn_cfg.lua
lua/gatekeeper.lua
lua/ggu.lua
lua/gk.lua
lua/gt.lua
lua/lls.lua
lua/sol.lua
sol/main.c

gatekeeper: rate limit log entries

---

gk/fib.c
gk/main.c
include/gatekeeper_fib.h
include/gatekeeper_gk.h
include/gatekeeper_net.h
lib/net.c
lls/arp.c
lls/nd.c
lua/dylib.lua
lua/example_of_dynamic_config_request.lua

gk: add functionality to flush flow tables

---

cps/main.c
ggu/main.c
gk/main.c
gt/main.c
include/gatekeeper_config.h
include/gatekeeper_launch.h
include/gatekeeper_net.h
lib/launch.c
lib/net.c
lls/main.c
lua/gatekeeper.lua
lua/net.lua
sol/main.c

config: make net compile-time parameters runtime parameters

---

ggu/main.c

ggu: verify UDP checksum

---

lib/net.c

Use ETH_RSS_IP as a general baseline for the hash functions to
support, and disable RSS if a device does not support any of them.
Use ETH_RSS_IPV4|ETH_RSS_IPV6 as a more specific expectation for
the hashes that the device should support, and issue a warning
if they don't.
This patch closes #152.

net: add additional checks for RSS hashes

---

gk/main.c
include/gatekeeper_gk.h
lua/gatekeeper.lua
lua/gk.lua

gk: log basic measurements

---

gt/main.c
lua/examples/policy.lua

gt: cast the parameters of policy lookup functions in C

---

ggu/main.c
include/gatekeeper_ggu.h
lua/gatekeeper.lua
lua/ggu.lua

These patches clean up the GGU configuration files and make them match the wiki documentation:
https://github.com/AltraMayor/gatekeeper/wiki/Functional-Block:-GGU

Clean up GGU configuration

---

cps/kni.c
cps/kni.h
cps/main.c
include/gatekeeper_net.h

Add the last pieces of functionality expected from the routing daemon.

Implement RTM_GETLINK and RTM_GETADDR

---

lua/gatekeeper/staticlib.lua
lua/net.lua

net: check for duplicate interface in Lua config

---

Makefile
README.md
cps/kni.c
lua/cps.lua

cps: automatically find KNI module if path not given

---

gk/fib.c
gk/main.c
include/gatekeeper_gk.h
lua/gatekeeper/staticlib.lua
lua/gk.lua

Clean up the GK configuration and make it match the documentation here:
https://github.com/AltraMayor/gatekeeper/wiki/Functional-Block:-GK

Clean up GK configuration

---

include/gatekeeper_lls.h
lls/cache.c
lls/main.c
lua/gatekeeper/staticlib.lua
lua/gk.lua
lua/gt.lua
lua/lls.lua

Clean up the LLS configuration and make it match the documentation here:
https://github.com/AltraMayor/gatekeeper/wiki/Functional-Block:-LLS

Clean up LLS configuration

---

lua/sol.lua

Clean up the Solicitor block configuration and make it match this documentation:
https://github.com/AltraMayor/gatekeeper/wiki/Functional-Block:-SOL

lua: clean up SOL config

---

cps/main.c
gt/main.c
include/gatekeeper_gt.h
lua/gatekeeper/staticlib.lua
lua/gt.lua

Clean up the GT configuration and make it match this documentation:
https://github.com/AltraMayor/gatekeeper/wiki/Functional-Block:-GT

Clean up GT config

---

lua/net.lua

Clean up the network configuration and make it match the documentation here:
https://github.com/AltraMayor/gatekeeper/wiki/Network

lua: clean up network config

---

gk/fib.c
gk/main.c
gt/main.c
include/gatekeeper_flow.h
include/gatekeeper_lpm.h
include/gatekeeper_net.h
lib/flow.c
lib/lpm.c
lls/nd.c

gatekeeper: reviewing `struct ip_flow`

---

config/dynamic.c
gkctl/main.c
include/gatekeeper_config.h
include/gatekeeper_net.h
lib/net.c
lua/dyn_cfg.lua
lua/gatekeeper/staticlib.lua
lua/main_config.lua
lua/net.lua
main/main.c
setup.sh

gatekeeper: turn to a constrained user after the boot

---

README.md

This PR reorganizes the README file and adds instructions for installation via packages.

Readme reorganization

---

gk/main.c

gk: correctly direct packets to the GGU

---

lua/gatekeeper/dylib.lua

gk: map forwarding action enums to strings

---

gk/main.c
include/gatekeeper_gk.h

gk: count packets GK transfers elsewhere

---

gk/main.c

gk: check IP support before lookup

---

lib/log_ratelimit.c

gatekeeper: log stats about suppressed messages

---

lib/net.c

This patch aims to resolve the https://github.com/AltraMayor/gatekeeper/pull/274#discussion_r289008188

net: update the call of rte_convert_rss_key()

---

include/gatekeeper_lls.h
lls/main.c

lls: silently discard ICMPv6 router advertisements

---

gk/main.c
lib/net.c

 net: check RSS hash key get updated correctly

---

lls/main.c

This pull request resolves the issue in https://github.com/AltraMayor/gatekeeper/pull/273#discussion_r291222931

Fix LLS memory issues for ARP and ND

---

config/dynamic.c
gt/main.c
include/gatekeeper_gt.h
lua/examples/example_of_dynamic_config_request.lua
lua/gatekeeper/dylib.lua

gt: incrementally update the Lua policy

---

gk/main.c

gk: respond to pings on front interface

---

lib/net.c

net: disable RSS when no support of rss_hash_conf_get()

---

gk/main.c
include/gatekeeper_gk.h
lua/examples/example_of_dynamic_config_request.lua
lua/gatekeeper/dylib.lua

gk: add functionality to log flow state

---

cps/main.c
ggu/main.c
lls/cache.c
lls/main.c
lls/nd.c

gatekeeper: take care of fragmented packets

---

bpf/granted.c
gk/bpf.c
gk/bpf.h
gk/main.c
include/gatekeeper_flow_bpf.h
include/gatekeeper_gk.h

gk: forwarding granted packets directly to their destinations

---

README.md
debian/changelog
debian/control
debian/devbind.sh
debian/gatekeeper.dirs
debian/gatekeeper.install
debian/gatekeeper.lintian-overrides
debian/rules

This PR updates the Debian packaging instructions for the latest sources, and the DPDK version of the packages in the installation instructions in the README file.

Packaging updates

---

gk/main.c

When the flow table is full, drop request entries. If it's a policy
decision entry, try to heuristically drop an entry once in order
to make room for the new entry.
Also remove the warning of when the flow table is full.

gk: drop request entries when flow table is full

---

gk/main.c
include/gatekeeper_gk.h
lua/gatekeeper/staticlib.lua
lua/gk.lua

If you want me to run performance tests before we merge Qiaobin's changes, just let me know. Otherwise, I will wait until Qiaobin's PR is merged and then I will rebase and test these changes.

gk: change scan interval unit to iterations

---

gk/main.c

As we will batch the flow and LPM lookups, it is cleaner
to now separate the ``switch..case``'s that follow the flow
and LPM lookups into their own functions that can be called
from process_pkts_front() and process_pkts_back().

gk: refactor flow and fib processing code

---

gk/main.c

This patch drops function drop_flow_entry_heuristically() and its
auxiliary function (i.e. find_flow_entry_candidate()). Thus, it avoids
going through the bucket to see if there's an expired entry when the
flow hash table is full.

 gk: drop drop_flow_entry_heuristically() and its auxiliary function

---

gk/main.c

After applying this patch, below is the performance:
| lcores | table size | GK Mpps rcvd (0%) | GK Mpps rcvd (50%) | GK Mpps rcvd (99%) | GK Mpps rcvd (mean) | cli Mpps sent (0%) | cli Mpps sent (50%) | cli Mpps sent (99%) | cli Mpps sent (mean) |
|--------|------------|-------------------|--------------------|--------------------|---------------------|--------------------|---------------------|---------------------|----------------------|
|  1  |  2^15  |       2.54        |        2.86        |        3.18        |        2.86         |       11.09        |        11.62        |        12.13        |         11.62         | 
|  1  |  2^20  |       1.92        |        2.45        |        2.59        |        2.38         |       9.73        |        11.56        |        12.52 …

gk: change prefetches from batched to interleaved

---

ggu/main.c
gk/main.c
include/gatekeeper_gk.h
include/gatekeeper_mailbox.h
sol/main.c

This pull request enables GK blocks to batch policy decisions requests in their mailboxes in order to batch the lookup of all involved flows.
This pull request closes #344

Batching lookup of flows to update them with policy decisions

---

cps/main.c

In the master branch, it fails to release the KNI devices when Gatekeeper stops, which is shown below:
```
GATEKEEPER CPS: The CPS block at lcore = 5 is exiting
GATEKEEPER GGU: The GK-GT unit at lcore = 3 is exiting
GATEKEEPER GK: The GK block at lcore = 1 is exiting
GATEKEEPER SOL: The Solicitor block at lcore = 4 is exiting
GATEKEEPER GK: The GK block at lcore = 2 is exiting
GATEKEEPER LLS: The LLS block at lcore = 0 is exiting
GATEKEEPER DYN CFG: The Dynamic Config block at lcore = 6 is exiting
KNI: Fail to release kni device
KNI: Fail to release kni device
```
The solution is to release the kni devices first and then remove the kernel module.

cps: release everything in reverse order in cleanup_cps()

---

cps/kni.c
cps/main.c
include/gatekeeper_cps.h
lua/cps.lua
lua/gatekeeper/staticlib.lua

 CPS: have a memory pool for ARP and ND requests

---

config/static.c
gk/main.c
include/gatekeeper_gk.h
include/gatekeeper_sol.h
lua/gatekeeper/staticlib.lua
lua/gk.lua
lua/main_config.lua
lua/sol.lua
sol/main.c

This patch closes #374 and #185

sol: have multiple blocks to spread the load from GK blocks

---

gk/main.c
gt/main.c
include/gatekeeper_net.h
lib/ipip.c
lib/net.c
lls/cache.c
lua/gatekeeper/staticlib.lua
lua/net.lua

See documentation here:
https://github.com/AltraMayor/gatekeeper/wiki/Network#IPv4_Checksum_Offloading

Remove dependencies on IPv4 hardware checksums

---

gt/main.c

This patch allows Grantor servers to support a single gateway
for non-local traffic and still avoid having an LPM lookup.
It also demonstrates the network configurations
for a deployment scenario, as described in #267 and #417.

gt: reply to gateway for non-local traffic

---

lib/flow.c

flow: do not panic on unknown flow types

---

debian/changelog

Updates Debian/Ubuntu packaging for Gatekeeper 1.0.0.

debian: version 1.0.0

---

gk/fib.c
gk/main.c
include/gatekeeper_gk.h
lua/gatekeeper/staticlib.lua
lua/gk.lua

gk: eliminate parameters max number of fib entries

---

gk/fib.c

Pull request #447 introduced a bug that leads to a segmentation
fault during the initialization when only IPv4 or only IPv6 is
set up but the parameter `gk_conf->max_num_ipv4_rules` or
`gk_conf->max_num_ipv6_rules` of the disable stack is not zero.
See `init_fib_tbl()` in `gk/fib.c` for details.
This patch fixes the bug and adds warning messages and an assert
to the code.

gk: allow single stack (i.e. either IPv4 or IPv6)

---

lib/net.c

`getlogin_r()` was used to obtain a user name to be used as the first argument for the subsequent `initgroups()` call. However, `getlogin_r()` returns the user name of the logged in user which started Gatekeeper (that is, root), while the correct argument to `initgroups()` is the name of the unprivileged user defined in `net.lua`.
Furthermore, `getlogin_r()` doesn't work when the process has no controlling terminal, as is the case for processes started from an init system such as systemd.

net: replace getlogin_r with getpwuid

---

.gitmodules
README.md
debian/changelog
debian/control

Ubuntu 20.04

---

cps/kni.c
lib/l2.c

The following patches improve some log entries according to the feedback we've received from a production deployment.

Improve log entries for production

---

lib/acl.c

Extension callback functions are used to deal with packets whose headers are larger than usual due to extensions.
Given that these functions return the same output for the same packet, there is no need to call them multiple times when they don't match a packet.
To see an example of the use of duplicate extension functions, see `register_icmp6_filters()`.

acl: run extension functions only once per packet

---

lib/net.c

The addresses of the front and back interfaces of Gatekeeper cannot be neighbors, that is, they must be in different subnets.
This is necessary to guarantee that attackers cannot bypass Gatekeeper.
The problem was first reported in issue #519.

net: front and back addresses cannot be in the same subnet

---

config/dynamic.c
cps/main.c
ggu/main.c
gk/main.c
gt/main.c
include/gatekeeper_log_ratelimit.h
lib/log_ratelimit.c
lls/main.c
sol/main.c

This is the initial pull request to resolve #497

gatekeeper: add log info to log_ratelimit_state

---

lib/log_ratelimit.c
lua/examples/example_of_dynamic_config_request.lua
lua/gatekeeper/staticlib.lua
main/main.c

This pull request brings a number of small improvements to the new log subsystem.

Small improvements to the new log subsystem

---

.gitmodules
Makefile
README.md
config/dynamic.c
cps/main.c
ggu/main.c
gk/main.c
gt/lua_lpm.c
gt/main.c
include/coro.h
include/gatekeeper_main.h
include/gatekeeper_net.h
include/gatekeeper_sol.h
lib/launch.c
lib/net.c
lls/main.c
lua/gatekeeper/policylib.lua
setup.sh
sol/main.c

This pull request closes #502.

 Update Gatekeeper's DPDK to LTS 20.11.1

---

lib/net.c

When a NIC does not support an Ethernet or ntuple filter, it's helpful to know which flow failed to install. This information helps diagnose issues in production and debug Gatekeeper. This patch adds a human-readable description of the failing flow and includes more details to related log entries.

lib/net: improve log entries for hardware flows

---

lib/net.c

After upgrading Gatekeeper's DPDK, Gatekeeper is not booting with bond interfaces.  This issue is identified with log entries similar to the one below:
`memzone eth_p1_q0_rx_ring does not justify the requested attributes`
The example log entry above and others may differ on the name of the queue that triggers the issue. In the example above, the name of the queue is `eth_p1_q0_rx_ring`.
The solution consists in allocating the RX and TX queues on the same NUMA socket to which the underlying Ethernet device is connected; see `configure_queue()` edited in this pull request for more details. Gatekeeper was using the NUMA node of the block responsible for the queue.
Here is a backtrace when the issue is triggered to serve as a reference:
```gdb
(gdb) bt
#0  rte_eth_dma_zone_reserve …
```

lib/net: boot with bond interfaces

---

gk/main.c
gt/main.c
include/gatekeeper_flow.h
lib/flow.c

This pull request is a forward port of pull request #596, which targeted version 1.0 of Gatekeeper. This pull request significantly improves the code of pull request #596.

gk: enhance the healing of the flow table

---

gt/lua_lpm.c
lua/gatekeeper/policylib.lua

Gatekeeper v1.1 RC1 has been chiefly tested on Gatekeeper servers so far. This pull request fixes bugs that only show up on Grantor servers.

gt: fix bugs

---

gk/main.c

This pull request adds the source and destination addresses of packets coming from the back interface when they trigger an error.
The extra information is meant to help with diagnosis in production.

gk: add information to log entries from the back interface

---

gk/main.c
gk/rt.c

The routing table (RT) has been requiring gateway addresses not to be included in the prefix of gateway and grantor RT entries. This commit removes this requirement for gateway entries but maintains it for grantor entries.
The motivation is to support default routes.
Without this commit, default routes are denied with log entries similar to the ones below:
```
DYC/9: check_gateway_prefix(0.0.0.0/0): gateway address is in prefix, so gateway is not a neighbor
DYC/9: check_gateway_prefix(::/0): gateway address is in prefix, so gateway is not a neighbor
```

gk: loosen verification of gateway RT entries

---

cps/main.c
ggu/main.c
gt/main.c
lib/acl.c
lls/cache.c
lls/main.c

This pull request closes #435.

Pktmbuf free

---

gt/lua_lpm.c
gt/main.c

As Lua policies evolve, they may increase the memory pressure on Lua. This pull request releases some of this pressure.
The long-term solution is to upgrade to LuaJIT v2.1 and to enable [GC64](https://blog.openresty.com/en/luajit-gc64-mode/) once LuaJIT v2.1 is stable.

gt: release memory pressure on Lua

---

Makefile
gk/main.c
include/gatekeeper_gk.h
include/gatekeeper_hash.h
lib/hash.c
lua/gatekeeper/staticlib.lua
lua/gk.lua

This pull request closes #375.

Add hopscotch hashing
